### PR TITLE
Unify definitions, formatting.

### PR DESCRIPTION
**Pull request by rkratky**

### CODE REVIEW

**Comment by lruzicka** [comment]
Jo, původně jsem nad tím taky uvažoval, že by tam byly celé věty. Já myslím ok.

**Comment by rkratky** [comment]
Někde byly, někde ne, tak jsem to sjednotil. Zbytek je kosmetický. Merguju tedy. Dík.

**Comment by lruzicka** [comment]
Pokud máš to repo na lokalu a asciidoctor, tak jenom spustit ten script a
můžeš a máš to updatovane.

Dne 4. 10. 2017 7:42 PM napsal uživatel "Robert Kratky" <
notifications@github.com>:

**Comment by rkratky** [comment]
Zrovna na to koukám -- asi bych ten skript upravil, aby předpokládal použití osobního forku toho repa, ne?

Tj. git push upstream.

**Comment by lruzicka** [comment]
A chceme, aby tam každý mohl z osobního repa pushnout?

Dne 4. 10. 2017 7:50 PM napsal uživatel "Robert Kratky" <
notifications@github.com>:

**Comment by rkratky** [comment]
Pravda, nechceme :-) Ale v tom případě by ten skript chtěl aspoň krátký koment, aby to lidi nemátlo.

**Comment by lruzicka** [comment]
To můžeme. Až přijdu domů, tak to tam dám.

Dne 4. 10. 2017 8:01 PM napsal uživatel "Robert Kratky" <
notifications@github.com>:

**Comment by bergerhoffer** [comment]
@laubai I'm not sure that I see bolded steps in the example doc that you shared. That looks totally fine to me. The only things I see bolded are GUI items, which is our recommendation for GUI items.

Below is an example of an old EAP doc that bolds the entire first sentence of a step. That is what we're saying not to do. Having a concise first sentence of a step on its own line, and the rest of the details in paragraphs, etc. below it should be sufficient. Though I've also seen instances where the first sentence of a step was bolded and it was in a giant paragraph and that is not good either.

https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html/Installation_Guide/sect-RPM_Installation.html#Install_JBoss_Enterprise_Application_Platform_6_RPM_Installation

**Pull request merged**
