### PR TITLE
GitHub-29: Providing a better emphasis example.

### LINKED ISSUE #29: Incorrect example of emphasis for a term
In the current guide it has the following example: 

Emphasis for a term | Use _this_ approach. -- | --

I don't think we should ever use italics to emphasise a word like 'this'. I cannot think of a scenario where this would be a legitimate use case. 

If we are adding italics, we should be doing so in accordance with the IBM Style Guide. 

For example, when you define a new term, the word you are defining can be in italics. 

I suggest either deleting this guidance, or rewriting with an example from IBM Style Guide.

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #29

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@rkratky or any other @redhat-documentation/adoc-styling-mark-up-conventions members still watching this project, can you take a look through the PRs that I've opened?

**Comment by samccann** [comment]
I would love to but I've been working on non-asciidoc files for the past 3 years. I've lost track on whether CCS actually supports this approach anymore. I'm not sure whom to ask that question. Maybe start with FCC/mod docs folks?

I think it's a great resource and sad to see it die.

**Review by ncbaratta — APPROVED** [review]
lgtm

**Comment by samccann** [comment]
@ncbaratta - do you know if we ever got the tools to work with things like ``[command]`oc get`` etc?

**Comment by ncbaratta** [comment]
@samccann I'm actually not sure what you're asking about.

**Comment by bergerhoffer** [comment]
@ncbaratta I think that @samccann is talking about the macros that are used in some of the examples, like `[command]` here:

```
Use the [command]`oc get` command to get a list of services.
```
You need to set the `:experimental:` attribute to be able to use them. I've never worked on a project that has used these, but I think (@rkratky can confirm) that the portal has supported their use since this guide was published, a few years ago.

**Comment by pmkovar** [comment]
I think this can be safely merged, thanks.

**Pull request merged**
